# Description: X Resize and Rotate extension client application
# URL: http://xorg.freedesktop.org

name=xrandr
version=1.3.5
release=1
source=(http://xorg.freedesktop.org/releases/individual/app/$name-$version.tar.bz2)
depends=(libX11 libXrandr)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr

   make -j $JOBS
   make DESTDIR=$PKG install
}
