# Description: X.Org xcmiscproto
# URL: http://xorg.freedesktop.org

name=xcmiscproto
version=1.2.2
release=1
source=(http://xorg.freedesktop.org/releases/individual/proto/$name-$version.tar.bz2)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr

   make -j $JOBS
   make DESTDIR=$PKG install
}
