# Description: Utility to configure and test X input devices
# URL: http://xorg.freedesktop.org

name=xinput
version=1.6.1
release=1
source=(http://xorg.freedesktop.org/releases/individual/app/$name-$version.tar.bz2)
depends=(libX11 libXext libXi libXrandr libXinerama)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr

   make -j $JOBS
   make DESTDIR=$PKG install
}
