# Description: X.Org kbproto
# URL: http://xorg.freedesktop.org

name=kbproto
version=1.0.6
release=1
source=(http://xorg.freedesktop.org/releases/individual/proto/$name-$version.tar.bz2)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr

   make
   make DESTDIR=$PKG install

   rm -r $PKG/usr/share/doc
}
