# Description: X authority file utility
# URL: http://xorg.freedesktop.org

name=xauth
version=1.0.8
release=1
source=(http://xorg.freedesktop.org/releases/individual/app/$name-$version.tar.bz2)
depends=(xorg-server libXmu libXv)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr

   make -j $JOBS
   make DESTDIR=$PKG install
}
