# Description: X.Org xf86-input-mouse driver
# URL: http://xorg.freedesktop.org

name=xf86-input-mouse
version=1.9.0
release=1
source=(http://xorg.freedesktop.org/releases/individual/driver/$name-$version.tar.bz2)
depends=xorg-server

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr

   make -j $JOBS
   make DESTDIR=$PKG install

   # Fix libtool files
   fix_la_files $PKG
}
