# Description: Create dependencies in Makefiles
# URL: http://xorg.freedesktop.org

name=makedepend
version=1.0.4
release=1
source=(http://xorg.freedesktop.org/releases/individual/util/$name-$version.tar.bz2)
depends=(xproto)

build() {
	cd $name-$version

	./configure --build=$BUILD \
                    --host=$HOST \
                    --prefix=/usr

	make -j $JOBS
	make DESTDIR=$PKG install
}
