# Description: TWM window manager
# URL: http://xorg.freedesktop.org

name=twm
version=1.0.7
release=1
source=(http://xorg.freedesktop.org/releases/individual/app/$name-$version.tar.bz2)
depends=(libX11 libXext libXt libXmu libICE libSM xproto)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr

   make -j $JOBS
   make DESTDIR=$PKG install
}
