# Description: X.Org font font-bh-ttf
# URL: http://xorg.freedesktop.org
depends=(mkfontdir mkfontscale fontconfig)

name=font-bh-ttf
version=1.0.3
release=1
source=(http://xorg.freedesktop.org/releases/individual/font/$name-$version.tar.bz2)

build() {
	cd $name-$version

	./configure --prefix=/usr

	make -j $JOBS
	make DESTDIR=$PKG install

	rm $PKG/usr/share/fonts/X11/TTF/fonts.{dir,scale}
}
