# Description: X.Org xf86vidmodeproto
# URL: http://xorg.freedesktop.org

name=xf86vidmodeproto
version=2.3.1
release=1
source=(http://xorg.freedesktop.org/releases/individual/proto/$name-$version.tar.bz2)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr

   make -j $JOBS
   make DESTDIR=$PKG install
}
