# Description: X input client library
# URL: http://xorg.freedesktop.org

name=libXi
version=1.7
release=1
source=(http://xorg.freedesktop.org/releases/individual/lib/$name-$version.tar.bz2)
depends=(libX11 libXext)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --enable-malloc0returnsnull

   make -j $JOBS
   make DESTDIR=$PKG install

   rm -r $PKG/usr/share/doc

   # Fix libtool files
   fix_la_files $PKG
}
