# Description: X.Org libxkbfile
# URL: http://xorg.freedesktop.org

name=libxkbfile
version=1.0.8
release=1
source=(http://xorg.freedesktop.org/releases/individual/lib/$name-$version.tar.bz2)
depends=(libX11 kbproto)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr

   make -j $JOBS
   make DESTDIR=$PKG install
   
   # Fix libtool files
   fix_la_files $PKG
}
