# Description: X Video extension client library
# URL: http://xorg.freedesktop.org

name=libXv
version=1.0.10
release=1
source=(http://xorg.freedesktop.org/releases/individual/lib/$name-$version.tar.bz2)
depends=(libX11 libXext videoproto)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --enable-malloc0returnsnull

   make
   make DESTDIR=$PKG install

   # Fix libtool files
   fix_la_files $PKG
}
