# Description: X.Org recordproto
# URL: http://xorg.freedesktop.org

name=recordproto
version=1.14.2
release=1
source=(http://xorg.freedesktop.org/releases/individual/proto/$name-$version.tar.bz2)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr

   make -j $JOBS
   make DESTDIR=$PKG install
   
   rm -r $PKG/usr/share/doc
}
