# Description: X Session Management client library
# URL: http://xorg.freedesktop.org

name=libSM
version=1.2.1
release=1
source=(http://xorg.freedesktop.org/releases/individual/lib/$name-$version.tar.bz2)
depends=(libICE xproto xtrans)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr

   make -j $JOBS
   make DESTDIR=$PKG install

   rm -r $PKG/usr/share/doc

   # Fix .la files
   find $PKG -name "*.la" -exec sed -i -e "/dependency_libs/s; /usr; $SYSROOT/usr;g" {} \; \
                          -exec sed -i -e "/libdir/s;'/usr;'$SYSROOT/usr;g" {} \;
}
