# Description: X.Org libXtst
# URL: http://xorg.freedesktop.org

name=libXtst
version=1.2.1
release=1
source=(http://xorg.freedesktop.org/releases/individual/lib/$name-$version.tar.bz2)
depends=(libX11 libXext libXi recordproto)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr

   make -j $JOBS
   make DESTDIR=$PKG install

   rm -r $PKG/usr/share/doc

   # Fix libtool files
   fix_la_files $PKG
}
