# Description: X client library
# URL: http://xorg.freedesktop.org

name=libX11
version=1.5.0
release=2
source=(http://xorg.freedesktop.org/releases/individual/lib/$name-$version.tar.bz2)
depends=(libxcb xextproto xtrans kbproto inputproto xf86bigfontproto xproto)

build() {
   cd $name-$version

   # Fix missing keysymdef.h file
   sed -i configure \
       -e "s|KEYSYMDEFDIR=.*|KEYSYMDEFDIR=\"$SYSROOT/usr/include/X11\"|"
   # Fix missing X11/X.h file when native compiling makekeys
   sed -i src/util/Makefile.in \
       -e "/X11_CFLAGS =/s|$| -I\"$SYSROOT/usr/include\"|"

  ./configure --build=$BUILD \
              --host=$HOST \
              --prefix=/usr \
              --enable-malloc0returnsnull

   make -j $JOBS
   make DESTDIR=$PKG install

   rm -r $PKG/usr/share/doc

   # Fix .la files
   find $PKG -name "*.la" -exec sed -i -e "/dependency_libs/s; /usr; $SYSROOT/usr;g" {} \; \
                          -exec sed -i -e "/libdir/s;'/usr;'$SYSROOT/usr;g" {} \;
}
