# Description: Library for handling input devices
# URL: http://www.freedesktop.org/wiki/Software/libinput

name=libinput
version=0.12.0
release=1
source=(http://www.freedesktop.org/software/$name/$name-$version.tar.xz)
depends=(mtdev systemd libevdev)

build() {
    cd $name-$version

    ./configure --build=$BUILD \
                --host=$HOST \
                --prefix=/usr \
                --disable-static \
                --disable-event-gui \
                --disable-tests 


    make -j $JOBS
    make DESTDIR=$PKG install

    # Fix libtool files
    fix_la_files $PKG
}
