# Description: X.Org xf86-input-keyboard driver
# URL: http://xorg.freedesktop.org

name=xf86-input-keyboard
version=1.6.2
release=1
source=(http://xorg.freedesktop.org/releases/individual/driver/$name-$version.tar.bz2)
depends=xorg-server

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr

   make -j $JOBS
   make DESTDIR=$PKG install

   # Fix libtool files
   fix_la_files $PKG
}
