# Description: X.Org libXt
# URL: http://xorg.freedesktop.org

name=libXt
version=1.1.3
release=1
source=(http://xorg.freedesktop.org/releases/individual/lib/$name-$version.tar.bz2)
depends=(libSM libX11 xproto kbproto)

build() {
   cd $name-$version

   # Fix missing X11/X.h file when native compiling makestrs
   sed -i util/Makefile.in \
       -e "/DEFAULT_INCLUDES =/s|$| -I\"$SYSROOT/usr/include\"|"

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --enable-malloc0returnsnull

   make -j $JOBS
   make DESTDIR=$PKG install

   rm -r $PKG/usr/share/doc

   # Fix libtool files
   fix_la_files $PKG
}
