# Description: xorg XKB keyboard description compiler
# URL: http://xorg.freedesktop.org

name=xkbcomp
version=1.2.4
release=1
source=(http://xorg.freedesktop.org/releases/individual/app/$name-$version.tar.bz2)
depends=(libX11 libxkbfile)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr

   make -j $JOBS
   make DESTDIR=$PKG install
}
