# Description: X Resize and Rotate extension client library
# URL: http://xorg.freedesktop.org

name=libXrandr
version=1.3.2
release=1
source=(http://xorg.freedesktop.org/releases/individual/lib/$name-$version.tar.bz2)
depends=(libX11 randrproto xextproto libXext libXrender renderproto)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --enable-malloc0returnsnull

   make -j $JOBS
   make DESTDIR=$PKG install

   # Fix .la files
   find $PKG -name "*.la" -exec sed -i -e "/dependency_libs/s; /usr; $SYSROOT/usr;g" {} \; \
                          -exec sed -i -e "/libdir/s;'/usr;'$SYSROOT/usr;g" {} \;
}
