# Description: X.Org's implementation of X11
# URL: http://xorg.freedesktop.org
depends=(xorg-server
         xf86-input-mouse
         xf86-input-keyboard
         xf86-input-evdev
         xf86-video-fbdev
         xkeyboard-config
         xinit
         xauth
         xterm
         xclock
         xinput
         xset
         xdpyinfo
         xrandr
         xrdb
         twm
         rgb
         sed
         font-bh-type1
         font-bh-ttf
         font-ms-ttf)

name=xorg
version=7.7
release=1
