# Description: X.Org libXpm
# URL: http://xorg.freedesktop.org

name=libXpm
version=3.5.11
release=1
source=(http://xorg.freedesktop.org/releases/individual/lib/$name-$version.tar.bz2)
depends=(xproto libX11 libXt xextproto libXext util-linux)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr

   make -j $JOBS
   make DESTDIR=$PKG install

   # Fix libtool files
   fix_la_files $PKG
}
