# Description: X.Org fixesproto
# URL: http://xorg.freedesktop.org

name=fixesproto
version=5.0
release=1
source=(http://xorg.freedesktop.org/releases/individual/proto/$name-$version.tar.bz2)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr

   make -j $JOBS
   make DESTDIR=$PKG install

   rm -rf $PKG/usr/share
}
