# Description: X.Org xtrans
# URL: http://xorg.freedesktop.org

name=xtrans
version=1.2.7
release=1
source=(http://xorg.freedesktop.org/releases/individual/lib/$name-$version.tar.bz2)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr

   make -j $JOBS
   make DESTDIR=$PKG install

   rm -r $PKG/usr/share/doc
}
