# Description: X.Org xf86miscproto
# URL: http://xorg.freedesktop.org

name=xf86miscproto
version=0.9.3
release=1
source=(http://xorg.freedesktop.org/releases/individual/proto/$name-$version.tar.bz2)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr

   make -j $JOBS
   make DESTDIR=$PKG install
}
