# Description: X Authorization routines
# URL: http://xorg.freedesktop.org

name=libXau
version=1.0.7
release=1
source=(http://xorg.freedesktop.org/releases/individual/lib/$name-$version.tar.bz2)
depends=xproto

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr

   make -j $JOBS
   make DESTDIR=$PKG install

   # Fix libtool files
   fix_la_files $PKG
}
