# Description: X Window System RGB database
# URL: http://xorg.freedesktop.org

name=rgb
version=1.0.5
release=1
source=(http://xorg.freedesktop.org/releases/individual/app/$name-$version.tar.bz2)
depends=xproto

build() {
   cd $name-$version

#  sed 's| pkg_failed=yes| pkg_failed=no|' -i configure

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr

   make -j $JOBS
   make DESTDIR=$PKG install
}
