# Description: A reference wayland compositor
# URL: http://wayland.freedesktop.org

name=weston
version=1.5.93
release=1
source=(http://wayland.freedesktop.org/releases/$name-$version.tar.xz
        disable-wayland-scanner-pkg-check.patch)
depends=(wayland pixman libxkbcommon libinput libpng libjpeg cairo linux-pam)

build() {
    cd $name-$version

    patch -p1 < $SRC/disable-wayland-scanner-pkg-check.patch

    autoreconf --install

    ./configure --build=$BUILD \
                --host=$HOST \
                --prefix=/usr \
                --disable-egl \
                --disable-static \
                --enable-xkbcommon \
                --enable-libinput-backend \
                --enable-setuid-install \
                --disable-xwayland \
                --disable-xwayland-test \
                --disable-x11-compositor \
                --disable-drm-compositor \
                --disable-wayland-compositor \
                --disable-headless-compositor \
                --disable-rpi-compositor \
                --disable-rdp-compositor \
                --enable-fbdev-compositor \
                --disable-screen-sharing \
                --disable-vaapi-recorder \
                --disable-simple-egl-clients \
                --disable-resize-optimization \
                --enable-weston-launch \
                --enable-clients \
                --enable-simple-clients \
                --enable-fullscreen-shell \
                --disable-colord \
                --disable-dbus \
                --disable-wcap-tools \
                --disable-libunwind \
                --enable-demo-clients-install \
                WESTON_NATIVE_BACKEND="fbdev-backend.so"

   make -j $JOBS
   make DESTDIR=$PKG install

   # Fix libtool files
   fix_la_files $PKG
}
