# Description: X.Org libxkbui
# URL: http://xorg.freedesktop.org

name=libxkbui
version=1.0.2
release=1
source=(http://xorg.freedesktop.org/releases/individual/lib/$name-$version.tar.bz2)
depends=(libX11 libXt libxkbfile)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr

   make -j $JOBS
   make DESTDIR=$PKG install

   # Fix libtool files
   fix_la_files $PKG
}
